version: '3.8'

services:
  galeproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: galeproxy
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/root/config.yaml
    volumes:
      - ./config.yaml:/root/config.yaml
    networks:
      - galeproxy-network

networks:
  galeproxy-network:
    driver: bridge